[package]
name = "vtg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
hyper-rustls = "0.24.1"
serde_json = "1.0.105"
form_urlencoded = "1.2.0"
serde = { version = "1.0", features = ["derive"] }
regex = "1.9.3"
regex-automata = "0.3.6"
lazy_static = "1.4.0"
rand = "0.8.5"
